# Navigation Links (导航链接配置)
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   (中文说明：若要链接到主页上的某个组件/板块，请将 URL 设置为 '#' 加上 'content/home/' 文件夹中对应的文件名。)
#   The weight parameter defines the order that the links will appear in.
#   (中文说明：weight 参数定义了链接出现的顺序，数字越小越靠前。)

main:
  - name: 实验室概况        # 首页/概况
    url: /
    weight: 10

  - name: 核心技术成果          # 对应 publication
    url: publication
    weight: 20

  - name: 实验平台与典型案例 # 对应 equipment
    url: equipment
    weight: 30

  - name: 团队科研人员      # 对应 people
    url: people
    weight: 40

  - name: 学术活动          # 对应 event
    url: event
    weight: 50

  - name: 合作交流动态          # 对应 post
    url: post
    weight: 60

  - name: 联系我们          # 对应 contact
    url: contact
    weight: 70