# Navigation Links (导航链接配置)
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   (中文说明：若要链接到主页上的某个组件/板块，请将 URL 设置为 '#' 加上 'content/home/' 文件夹中对应的文件名。)
#   The weight parameter defines the order that the links will appear in.
#   (中文说明：weight 参数定义了链接出现的顺序，数字越小越靠前。)

main:
  - name: 实验室概况     # 菜单栏显示的名称：导览
    url: /              # 链接地址：这里指向 'content/index.md' 根目录
    weight: 10          # 排序权重：10 (数字最小，显示在最左边)

  - name: 新闻动态       # 菜单栏显示的名称：新闻动态
    url: post           # 链接地址：这里指向 'content/post' (通常用于存放博客或新闻文章)
    weight: 20          # 排序权重：20 (排在 Tour 之后)



  - name: 团队科研人员        # 菜单栏显示的名称：成员/人物
    url: people         # 链接地址：指向 'content/people' (团队成员介绍)
    weight: 30          # 排序权重：30

  - name: 学术活动        # 菜单栏显示的名称：学术活动/会议
    url: event          # 链接地址：指向 'content/event'
    weight: 40          # 排序权重：40

  - name: 近年成果  # 菜单栏显示的名称：发表论文/出版物
    url: publication    # 链接地址：指向 'content/publication'
    weight: 50          # 排序权重：50

  - name: 实验平台与典型案例
    url: equipment  # 对应 content/equipment 文件夹
    weight: 60      # 调整这个数字，决定它排在第几个

  - name: 联系我们      # 菜单栏显示的名称：联系我们
    url: contact        # 链接地址：指向 'content/contact' 或联系页面
    weight: 70          # 排序权重：70 (排在最后)